# Generated by Django 2.1.7 on 2019-03-30 00:38

from django.db import migrations


def create_data(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    Customer(first_name="Zac", last_name="Zhu", email="zac_ju@163.com", phone="00000000",
             address="Shanghai", description="Mobile Developer").save()


class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
